"""empty message

Revision ID: 08fdc6c9b47c
Revises: 6bdcb9e99abc
Create Date: 2021-02-12 02:21:52.674470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fdc6c9b47c'
down_revision = '6bdcb9e99abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('Color', sa.String(length=80), nullable=False))
    op.create_foreign_key(None, 'products', 'brand', ['brand_id'], ['Brand_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'Color')
    # ### end Alembic commands ###
