"""empty message

Revision ID: 13768f254e69
Revises: 1429e35796c0
Create Date: 2021-02-07 16:00:30.223631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13768f254e69'
down_revision = '1429e35796c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'category', 'brand', ['brand_id'], ['Brand_id'])
    op.drop_column('products', 'cat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cat_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'category', type_='foreignkey')
    # ### end Alembic commands ###
