"""empty message

Revision ID: 1429e35796c0
Revises: 82d240cff65e
Create Date: 2021-02-07 15:26:07.078842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1429e35796c0'
down_revision = '82d240cff65e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'category', 'brand', ['brand_id'], ['Brand_id'])
    op.create_foreign_key(None, 'products', 'category', ['cat_id'], ['Category_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'category', type_='foreignkey')
    # ### end Alembic commands ###
