"""empty message

Revision ID: 1491ec090e3f
Revises: abc60c0f3cc5
Create Date: 2021-01-27 00:47:04.310875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1491ec090e3f'
down_revision = 'abc60c0f3cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'id')
    op.add_column('products', sa.Column('ProductImage', sa.String(length=120), nullable=False))
    op.add_column('products', sa.Column('Product_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('cat_Id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'category', ['cat_Id'], ['Category_id'])
    op.drop_column('products', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'cat_Id')
    op.drop_column('products', 'Product_id')
    op.drop_column('products', 'ProductImage')
    op.add_column('category', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
