"""empty message

Revision ID: 425b097ddb7f
Revises: 1491ec090e3f
Create Date: 2021-01-27 01:03:37.380286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425b097ddb7f'
down_revision = '1491ec090e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('ProductImage', sa.String(length=120), nullable=False))
    op.add_column('products', sa.Column('cat_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'category', ['cat_id'], ['Category_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'cat_id')
    op.drop_column('products', 'ProductImage')
    # ### end Alembic commands ###
