"""empty message

Revision ID: 4f6d5381fc38
Revises: a1b0b8661afa
Create Date: 2021-02-07 16:12:55.520261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6d5381fc38'
down_revision = 'a1b0b8661afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'category', 'brand', ['brand_id'], ['Brand_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    # ### end Alembic commands ###
