"""empty message

Revision ID: 5999a556d531
Revises: c2096fdca914
Create Date: 2021-02-07 16:34:12.197581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5999a556d531'
down_revision = 'c2096fdca914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('Brand_id', sa.Integer(), nullable=False),
    sa.Column('BrandName', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('Brand_id')
    )
    op.create_table('products',
    sa.Column('products_Product_id', sa.Integer(), nullable=False),
    sa.Column('products_ProductName', sa.String(length=30), nullable=False),
    sa.Column('products_Brand', sa.String(length=80), nullable=False),
    sa.Column('products_Price', sa.String(length=120), nullable=False),
    sa.Column('products_ProductInfo', sa.String(length=120), nullable=False),
    sa.Column('products_ProductImage', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('products_Product_id')
    )
    op.create_table('category',
    sa.Column('Category_id', sa.Integer(), nullable=False),
    sa.Column('CategoryName', sa.String(length=30), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.Brand_id'], ),
    sa.PrimaryKeyConstraint('Category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    op.drop_table('products')
    op.drop_table('brand')
    # ### end Alembic commands ###
