"""empty message

Revision ID: 5d607fcf92c7
Revises: b6c421cc0663
Create Date: 2021-02-11 20:21:32.241003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d607fcf92c7'
down_revision = 'b6c421cc0663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'products', 'brand', ['brand_id'], ['Brand_id'])
    op.add_column('user', sa.Column('Phone', sa.Numeric(precision=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'Phone')
    op.drop_constraint(None, 'products', type_='foreignkey')
    # ### end Alembic commands ###
