"""empty message

Revision ID: 6bdcb9e99abc
Revises: 5d607fcf92c7
Create Date: 2021-02-11 20:22:44.316505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdcb9e99abc'
down_revision = '5d607fcf92c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'products', 'brand', ['brand_id'], ['Brand_id'])
    op.add_column('user', sa.Column('Phone', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'Phone')
    op.drop_constraint(None, 'products', type_='foreignkey')
    # ### end Alembic commands ###
