"""empty message

Revision ID: 7b26abf6701d
Revises: c9e6124a5622
Create Date: 2021-01-27 01:15:26.459908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b26abf6701d'
down_revision = 'c9e6124a5622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'CategoryName')
    op.create_foreign_key(None, 'products', 'category', ['cat_id'], ['Category_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.add_column('category', sa.Column('CategoryName', sa.TEXT(length=30), nullable=False))
    # ### end Alembic commands ###
