"""empty message

Revision ID: 82d240cff65e
Revises: 20fbb41adb0b
Create Date: 2021-02-07 15:21:37.989854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d240cff65e'
down_revision = '20fbb41adb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('Brand_id', sa.Integer(), nullable=False),
    sa.Column('BrandName', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('Brand_id')
    )
    op.add_column('category', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'category', 'brand', ['brand_id'], ['Brand_id'])
    op.create_foreign_key(None, 'products', 'category', ['cat_id'], ['Category_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'brand_id')
    op.drop_table('brand')
    # ### end Alembic commands ###
