"""empty message

Revision ID: 874be8d8b9bc
Revises: 91d17f60e2bf
Create Date: 2021-02-11 02:05:41.259694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874be8d8b9bc'
down_revision = '91d17f60e2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'brand', ['brand_id'], ['Brand_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'brand_id')
    # ### end Alembic commands ###
