"""empty message

Revision ID: 927d719cb76e
Revises: 
Create Date: 2021-01-27 00:31:17.826852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927d719cb76e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('Category_Id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('ProductImage', sa.String(length=120), nullable=False))
    op.create_foreign_key(None, 'products', 'category', ['Category_Id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'ProductImage')
    op.drop_column('products', 'Category_Id')
    # ### end Alembic commands ###
