"""empty message

Revision ID: a1b0b8661afa
Revises: 5b84a27995e0
Create Date: 2021-02-07 16:10:02.656642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b0b8661afa'
down_revision = '5b84a27995e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'category', 'brand', ['brand_id'], ['Brand_id'])
    op.add_column('products', sa.Column('cat_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'category', ['cat_id'], ['Category_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'cat_id')
    op.drop_constraint(None, 'category', type_='foreignkey')
    # ### end Alembic commands ###
