"""empty message

Revision ID: a39713386d90
Revises: 0b4f1a441bcb
Create Date: 2021-02-11 01:26:00.024161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39713386d90'
down_revision = '0b4f1a441bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('Product_id', sa.Integer(), nullable=False),
    sa.Column('ProductName', sa.String(length=30), nullable=False),
    sa.Column('Size', sa.Numeric(precision=80), nullable=False),
    sa.Column('Price', sa.Numeric(precision=120), nullable=False),
    sa.Column('ProductInfo', sa.String(length=120), nullable=False),
    sa.Column('Material', sa.String(length=120), nullable=False),
    sa.Column('Stock', sa.Numeric(precision=60), nullable=False),
    sa.Column('ProductImage_1', sa.String(length=120), nullable=False),
    sa.Column('ProductImage_2', sa.String(length=120), nullable=False),
    sa.Column('Brand', sa.String(length=30), nullable=False),
    sa.Column('Category', sa.String(length=30), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['category.Category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('Product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
