"""empty message

Revision ID: a5fe2c0bc55b
Revises: 13768f254e69
Create Date: 2021-02-07 16:02:14.592829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5fe2c0bc55b'
down_revision = '13768f254e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'category', 'brand', ['brand_id'], ['Brand_id'])
    op.drop_column('products', 'cat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cat_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'category', type_='foreignkey')
    # ### end Alembic commands ###
