"""empty message

Revision ID: b6c421cc0663
Revises: 6db07285d6e6
Create Date: 2021-02-11 20:16:06.312433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c421cc0663'
down_revision = '6db07285d6e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'products', 'brand', ['brand_id'], ['Brand_id'])
    op.add_column('user', sa.Column('Phone', sa.Numeric(precision=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'Phone')
    op.drop_constraint(None, 'products', type_='foreignkey')
    # ### end Alembic commands ###
